db1:
  host: localhost
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: collabfieldmaster
  pool: 40
  timeout: 5000  
  username: root
  password: mysqlCT5
  #socket: /tmp/mysql.sock


development:
  adapter: mysql2
  database: collabfieldmaster
  pool: 40
  timeout: 5000  
  username: root
  password: mysqlCT5
  host: localhost
  #socket: /tmp/mysql.sock 